"Category: Animal":
  # Source
  - animal/
"Category: Image":
  # Source
  - image/
"Category: Nsfw":
  # Source
  - nsfw/
"Category: OniiTools":
  # Source
  - oniitools/
"Category: Perform":
  # Source
  - perform/
