[tool.black]
line-length = 99
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 99

[flake8]
ignore = E203, E266, E501, W503, F403, F401
max-line-length = 99
max-complexity = 18
select = B,C,E,F,W,T4,B9
