name: black

on: [push, pull_request]


jobs:
  mypy:
    name: Style Check with Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.9"
      - run: "python -m pip install black"
        name: Install black
      - run: "python -m black -l 99 --check --diff ."
        name: Style checking with black

# thanks sinbad & jack
