name: isort

on: [push, pull_request]


jobs:
  mypy:
    name: Style Check with Isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.9"
      - run: "python -m pip install isort"
        name: Install isort
      - run: "python -m isort --check-only --diff --profile black -l 99 ."
        name: Style checking with isort
